# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SOEN 357 Mini Project
email: nathangrenier01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This page was made to host blog posts about the mini project for Concordia's SOEN 357 User Interface Design Course.
github_username: NathanGrenier
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Canada/Eastern # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Nathan Grenier"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Third Year Software Engineering Student at Concordia University"
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    - label: "Figma Prototype"
      icon: "fa-brands fa-figma"
      url: "https://www.figma.com/design/VNZzTFGUborc8Uvylvo2dC/Prototypes?node-id=20-1987&t=pN5y5PAPDW3jF4L7-1"
    - label: "Figma User Personas"
      icon: "fa-brands fa-figma"
      url: "https://www.figma.com/board/8aKtgnHVLFzGfnBt6miREo/User-Personas?node-id=0-1&t=TgFMl9tZ5ph4yiuV-1"
    - label: "Figma User Journey Map"
      icon: "fa-brands fa-figma"
      url: "https://www.figma.com/board/OoeyaqiEbeca7exafm9PR9/User-Journey-Maps?node-id=0-1&t=amALUSS4h1HAijSH-1"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NathanGrenier/SOEN-357-Mini"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NathanGrenier/SOEN-357-Mini"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
